# Generated by Django 2.0.5 on 2018-05-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
